#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : libjcat
Version  : 0.2.3
Release  : 11
URL      : https://github.com/hughsie/libjcat/archive/0.2.3/libjcat-0.2.3.tar.gz
Source0  : https://github.com/hughsie/libjcat/archive/0.2.3/libjcat-0.2.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libjcat-bin = %{version}-%{release}
Requires: libjcat-data = %{version}-%{release}
Requires: libjcat-lib = %{version}-%{release}
Requires: libjcat-license = %{version}-%{release}
Requires: libjcat-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : gnutls-dev
BuildRequires : gpgme-dev
BuildRequires : json-glib-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libjcat
=======
This library allows reading and writing gzip-compressed JSON catalog files,
which can be used to store GPG, PKCS-7 and SHA-256 checksums for each file.

%package bin
Summary: bin components for the libjcat package.
Group: Binaries
Requires: libjcat-data = %{version}-%{release}
Requires: libjcat-license = %{version}-%{release}

%description bin
bin components for the libjcat package.


%package data
Summary: data components for the libjcat package.
Group: Data

%description data
data components for the libjcat package.


%package dev
Summary: dev components for the libjcat package.
Group: Development
Requires: libjcat-lib = %{version}-%{release}
Requires: libjcat-bin = %{version}-%{release}
Requires: libjcat-data = %{version}-%{release}
Provides: libjcat-devel = %{version}-%{release}
Requires: libjcat = %{version}-%{release}

%description dev
dev components for the libjcat package.


%package lib
Summary: lib components for the libjcat package.
Group: Libraries
Requires: libjcat-data = %{version}-%{release}
Requires: libjcat-license = %{version}-%{release}

%description lib
lib components for the libjcat package.


%package license
Summary: license components for the libjcat package.
Group: Default

%description license
license components for the libjcat package.


%package man
Summary: man components for the libjcat package.
Group: Default

%description man
man components for the libjcat package.


%package tests
Summary: tests components for the libjcat package.
Group: Default
Requires: libjcat = %{version}-%{release}

%description tests
tests components for the libjcat package.


%prep
%setup -q -n libjcat-0.2.3
cd %{_builddir}/libjcat-0.2.3
pushd ..
cp -a libjcat-0.2.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738595420
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :
cd ../buildavx2;
meson test -C builddir --print-errorlogs || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libjcat
cp %{_builddir}/libjcat-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libjcat/b386b371ce94933e63ced1052aa72a60da5485ff || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/jcat-tool
/usr/bin/jcat-tool

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Jcat-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/jcat.deps
/usr/share/vala/vapi/jcat.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libjcat-1/jcat.h
/usr/include/libjcat-1/libjcat/jcat-blob.h
/usr/include/libjcat-1/libjcat/jcat-bt-checkpoint.h
/usr/include/libjcat-1/libjcat/jcat-bt-verifier.h
/usr/include/libjcat-1/libjcat/jcat-common.h
/usr/include/libjcat-1/libjcat/jcat-compile.h
/usr/include/libjcat-1/libjcat/jcat-context.h
/usr/include/libjcat-1/libjcat/jcat-engine.h
/usr/include/libjcat-1/libjcat/jcat-file.h
/usr/include/libjcat-1/libjcat/jcat-item.h
/usr/include/libjcat-1/libjcat/jcat-result.h
/usr/include/libjcat-1/libjcat/jcat-version.h
/usr/lib64/libjcat.so
/usr/lib64/pkgconfig/jcat.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libjcat.so.1.0.0
/usr/lib64/libjcat.so.1
/usr/lib64/libjcat.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libjcat/b386b371ce94933e63ced1052aa72a60da5485ff

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/jcat-tool.1

%files tests
%defattr(-,root,root,-)
/V3/usr/libexec/installed-tests/libjcat/jcat-self-test
/usr/libexec/installed-tests/libjcat/jcat-self-test
/usr/share/installed-tests/libjcat/colorhug/firmware.bin
/usr/share/installed-tests/libjcat/colorhug/firmware.bin.asc
/usr/share/installed-tests/libjcat/colorhug/firmware.bin.ed25519
/usr/share/installed-tests/libjcat/colorhug/firmware.bin.p7b
/usr/share/installed-tests/libjcat/colorhug/firmware.bin.p7c
/usr/share/installed-tests/libjcat/colorhug/firmware.bin.sha256.p7c
/usr/share/installed-tests/libjcat/libjcat.test
/usr/share/installed-tests/libjcat/pki/GPG-KEY-Linux-Vendor-Firmware-Service
/usr/share/installed-tests/libjcat/pki/LVFS-CA.pem
/usr/share/installed-tests/libjcat/pki/test.ed25519
/usr/share/installed-tests/libjcat/pki/test.pem
/usr/share/installed-tests/libjcat/secret.ed25519
/usr/share/installed-tests/libjcat/test.btcheckpoint
/usr/share/installed-tests/libjcat/test.btverifier
